### ISSUE TITLE
py27跑不动，发个精简版的

### ISSUE THREAD

**Issue by Delectate** [sincerefly/IDCardQuery#2]
str_x = input('input:')
str_x = str(str_x)
 
tmpsum = int(str_x[0])*7 + int(str_x[1])*9 + int(str_x[2])*10 + int(str_x[3])*5 + int(str_x[4])*8 \
        + int(str_x[5])*4 + int(str_x[6])*2 + int(str_x[7])*1 + int(str_x[8])*6 + int(str_x[9])*3 \
        + int(str_x[10])*7 + int(str_x[11])*9 + int(str_x[12])*10 + int(str_x[13])*5 \
        + int(str_x[14])*8 + int(str_x[15])*4 + int(str_x[16])*2;
 
remainder = tmpsum % 11

maptable = {0: '1', 1: '0', 2: 'x', 3: '9', 4: '8', 5: '7', 6: '6', 7: '5', 8: '4', 9: '3', 10: '2'}
if maptable[remainder] == str_x[17]:
    print(u'<身份证合法>')

else :
    print(u'<身份证不合法>')

**Comment by sincerefly** [comment]
感谢提醒，之前的代码没有指定编码，导致py2.7中文错误
