### ISSUE TITLE
加一个js版放在/docs里资源写相对路径开git-pages，就可以在线使用?

### ISSUE THREAD

**Issue by biluohc** [sincerefly/IDCardQuery#3]

**Comment by sincerefly** [comment]
https://github.com/sincerefly/IDCardQuery/blob/master/python/data.json
把这个json数据存cdn上，用js直接加载解析就可以了。

**Comment by sincerefly** [comment]
或者直接用github的raw地址：
https://raw.githubusercontent.com/sincerefly/IDCardQuery/master/python/data.json
国内访问速度可能会比较慢

**Comment by biluohc** [comment]
你来写？ 我暂时没空，忙于毕设。

**Comment by sincerefly** [comment]
晚上吧,,,,,,,,,,
